import { Response } from 'express';
import { AuthRequest } from '../middleware/auth';
import { User } from '../models/User';
import { ProblemRegistryService } from '../services/problemRegistry.service';

interface RoadmapDefinition {
    id: string;
    name: string;
    description: string;
    difficulty: 'Easy' | 'Medium' | 'Hard';
    problemIds: string[];
}

const ROADMAPS: RoadmapDefinition[] = [
    {
        id: 'beginner',
        name: 'Beginner Core',
        description: 'Master arrays, strings, hashing, linked lists, stacks, queues, basic trees, recursion and binary search.',
        difficulty: 'Easy',
        problemIds: [
        "contains-duplicate",
        "valid-anagram",
        "two-sum",
        "remove-duplicates-from-sorted-array",
        "remove-element",
        "valid-palindrome",
        "is-subsequence",
        "majority-element",
        "binary-search",
        "search-insert-position",
        "guess-number-higher-or-lower",
        "sqrtx",
        "peak-index-in-a-mountain-array",
        "reverse-linked-list",
        "middle-of-the-linked-list",
        "merge-two-sorted-lists",
        "linked-list-cycle",
        "remove-linked-list-elements",
        "delete-node-in-a-linked-list",
        "palindrome-linked-list",
        "valid-parentheses",
        "implement-stack-using-queues",
        "implement-queue-using-stacks",
        "baseball-game",
        "backspace-string-compare",
        "next-greater-element-i",
        "min-stack",
        "maximum-depth-of-binary-tree",
        "same-tree",
        "invert-binary-tree",
        "symmetric-tree",
        "path-sum",
        "balanced-binary-tree",
        "fibonacci-number",
        "climbing-stairs",
        "pascals-triangle",
        "powx-n",
        "find-minimum-and-maximum-in-array",
        "move-zeroes",
        "reverse-array",
        "single-number",
        "arranging-coins",
        "first-bad-version",
        "valid-perfect-square",
        "counting-bits",
        "missing-number",
        "number-of-1-bits",
        "power-of-two",
        "reverse-bits",
        "min-cost-climbing-stairs"
]
    },
    {
        id: 'faang',
        name: 'FAANG Premium',
        description: 'Master the interview patterns repeatedly asked by Meta, Google, Amazon, Microsoft and Apple.',
        difficulty: 'Medium',
        problemIds: [
        "top-k-frequent-elements",
        "product-of-array-except-self",
        "encode-and-decode-strings",
        "longest-consecutive-sequence",
        "group-anagrams",
        "majority-element-ii",
        "container-with-most-water",
        "3sum",
        "4sum",
        "sort-colors",
        "trapping-rain-water",
        "best-time-to-buy-and-sell-stock",
        "longest-substring-without-repeating-characters",
        "longest-repeating-character-replacement",
        "permutation-in-string",
        "minimum-window-substring",
        "sliding-window-maximum",
        "search-in-rotated-sorted-array",
        "find-minimum-in-rotated-sorted-array",
        "koko-eating-bananas",
        "capacity-to-ship-packages-within-d-days",
        "median-of-two-sorted-arrays",
        "add-two-numbers",
        "reorder-list",
        "copy-list-with-random-pointer",
        "lru-cache",
        "remove-nth-node-from-end-of-list",
        "reverse-nodes-in-k-group",
        "daily-temperatures",
        "car-fleet",
        "evaluate-reverse-polish-notation",
        "largest-rectangle-in-histogram",
        "binary-tree-level-order-traversal",
        "lowest-common-ancestor-of-a-binary-search-tree",
        "binary-tree-right-side-view",
        "diameter-of-binary-tree",
        "serialize-and-deserialize-binary-tree",
        "validate-binary-search-tree",
        "kth-smallest-element-in-a-bst",
        "k-closest-points-to-origin",
        "last-stone-weight",
        "task-scheduler",
        "find-median-from-data-stream",
        "number-of-islands",
        "clone-graph",
        "rotting-oranges",
        "pacific-atlantic-water-flow",
        "course-schedule",
        "subsets",
        "combination-sum",
        "combination-sum-ii",
        "permutations",
        "letter-combinations-of-a-phone-number",
        "generate-parentheses",
        "implement-trie-prefix-tree",
        "design-add-and-search-words-data-structure",
        "word-search-ii",
        "house-robber",
        "house-robber-ii",
        "coin-change",
        "partition-equal-subset-sum",
        "longest-increasing-subsequence",
        "decode-ways",
        "unique-paths",
        "interleaving-string",
        "jump-game",
        "longest-common-subsequence",
        "longest-palindromic-substring",
        "maximal-square",
        "maximum-product-subarray",
        "minimum-path-sum",
        "palindromic-substrings",
        "target-sum",
        "word-break",
        "find-all-duplicates-in-an-array",
        "next-permutation",
        "rotate-array",
        "set-matrix-zeroes",
        "spiral-matrix",
        "palindrome-partitioning",
        "subsets-ii",
        "word-search",
        "find-first-and-last-position-of-element-in-sorted-array",
        "find-peak-element",
        "peak-index-in-a-mountain-array",
        "search-a-2d-matrix",
        "single-element-in-a-sorted-array",
        "maximum-xor-of-two-numbers-in-an-array",
        "single-number-ii",
        "sum-of-two-integers"
]
    },
    {
        id: 'amazon',
        name: 'Amazon Ultimate',
        description: 'Focus on Amazon OA + SDE interview patterns covering matrix, window, trees, and graphs.',
        difficulty: 'Medium',
        problemIds: [
        "spiral-matrix",
        "set-matrix-zeroes",
        "rotate-image",
        "game-of-life",
        "search-a-2d-matrix",
        "minimum-size-subarray-sum",
        "fruit-into-baskets",
        "maximum-average-subarray-i",
        "longest-ones",
        "max-consecutive-ones-iii",
        "binary-tree-zigzag-level-order-traversal",
        "binary-tree-vertical-order-traversal",
        "path-sum",
        "binary-tree-maximum-path-sum",
        "flatten-binary-tree-to-linked-list",
        "number-of-provinces",
        "surrounded-regions",
        "word-ladder",
        "open-the-lock",
        "network-delay-time",
        "cheapest-flights-within-k-stops",
        "reconstruct-itinerary",
        "alien-dictionary",
        "merge-k-sorted-lists",
        "top-k-frequent-words",
        "kth-largest-element-in-an-array",
        "ipo",
        "merge-intervals",
        "insert-interval",
        "non-overlapping-intervals",
        "meeting-rooms",
        "jump-game",
        "gas-station",
        "partition-labels",
        "word-break",
        "target-sum",
        "longest-common-subsequence",
        "edit-distance",
        "clone-graph",
        "course-schedule",
        "graph-valid-tree",
        "max-area-of-island",
        "min-cost-to-connect-all-points",
        "number-of-connected-components-in-an-undirected-graph",
        "number-of-islands",
        "pacific-atlantic-water-flow",
        "redundant-connection",
        "rotting-oranges",
        "find-all-duplicates-in-an-array",
        "group-anagrams",
        "longest-consecutive-sequence",
        "next-permutation",
        "product-of-array-except-self",
        "rotate-array",
        "sort-colors",
        "top-k-frequent-elements",
        "combination-sum-ii",
        "combination-sum",
        "letter-combinations-of-a-phone-number",
        "palindrome-partitioning",
        "permutations",
        "subsets-ii",
        "subsets",
        "word-search",
        "capacity-to-ship-packages-within-d-days",
        "find-first-and-last-position-of-element-in-sorted-array",
        "find-minimum-in-rotated-sorted-array",
        "find-peak-element",
        "koko-eating-bananas",
        "peak-index-in-a-mountain-array",
        "search-in-rotated-sorted-array",
        "single-element-in-a-sorted-array",
        "maximum-xor-of-two-numbers-in-an-array",
        "single-number-ii",
        "sum-of-two-integers"
]
    },
    {
        id: 'google',
        name: 'Google Advanced',
        description: "Prepare for Google's harder algorithmic rounds involving advanced graphs, trees, union-find, and DP.",
        difficulty: 'Hard',
        problemIds: [
        "alien-dictionary",
        "redundant-connection",
        "critical-connections-in-a-network",
        "min-cost-to-connect-all-points",
        "swim-in-rising-water",
        "reconstruct-itinerary",
        "recover-binary-search-tree",
        "binary-tree-cameras",
        "count-complete-tree-nodes",
        "all-nodes-distance-k-in-binary-tree",
        "maximum-width-of-binary-tree",
        "range-sum-query-mutable",
        "count-of-smaller-numbers-after-self",
        "falling-squares",
        "number-of-connected-components-in-an-undirected-graph",
        "accounts-merge",
        "graph-valid-tree",
        "n-queens-ii",
        "sudoku-solver",
        "word-search-ii",
        "expression-add-operators",
        "burst-balloons",
        "cherry-pickup",
        "distinct-subsequences",
        "regular-expression-matching",
        "wildcard-matching",
        "longest-palindromic-subsequence",
        "stone-game",
        "split-array-largest-sum",
        "minimize-max-distance-to-gas-station",
        "find-k-th-smallest-pair-distance",
        "candy",
        "queue-reconstruction-by-height",
        "hand-of-straights",
        "word-ladder",
        "n-queens",
        "median-of-two-sorted-arrays",
        "edit-distance",
        "longest-increasing-path-in-a-matrix",
        "find-median-from-data-stream",
        "ipo",
        "merge-k-sorted-lists",
        "lfu-cache",
        "minimum-window-substring",
        "sliding-window-maximum",
        "largest-rectangle-in-histogram",
        "binary-tree-maximum-path-sum",
        "serialize-and-deserialize-binary-tree",
        "trapping-rain-water",
        "contains-duplicate",
        "contains-duplicate",
        "contains-duplicate",
        "contains-duplicate",
        "contains-duplicate",
        "contains-duplicate",
        "contains-duplicate",
        "contains-duplicate",
        "contains-duplicate",
        "contains-duplicate",
        "contains-duplicate",
        "contains-duplicate",
        "contains-duplicate",
        "contains-duplicate",
        "contains-duplicate",
        "contains-duplicate",
        "contains-duplicate",
        "contains-duplicate",
        "contains-duplicate",
        "contains-duplicate",
        "contains-duplicate"
]
    },
    {
        id: 'thirtyDays',
        name: '30-Day Blitz',
        description: 'One high-impact interview problem every day for 30 days.',
        difficulty: 'Medium',
        problemIds: [
        "two-sum",
        "contains-duplicate",
        "valid-anagram",
        "product-of-array-except-self",
        "group-anagrams",
        "top-k-frequent-elements",
        "longest-consecutive-sequence",
        "valid-parentheses",
        "binary-search",
        "search-in-rotated-sorted-array",
        "container-with-most-water",
        "3sum",
        "best-time-to-buy-and-sell-stock",
        "longest-substring-without-repeating-characters",
        "merge-intervals",
        "insert-interval",
        "number-of-islands",
        "clone-graph",
        "course-schedule",
        "house-robber",
        "coin-change",
        "kth-smallest-element-in-a-bst",
        "lowest-common-ancestor-of-a-binary-search-tree",
        "combination-sum",
        "subsets",
        "generate-parentheses",
        "lru-cache",
        "find-median-from-data-stream",
        "word-break",
        "longest-increasing-subsequence"
]
    },
    {
        id: 'sixtyDays',
        name: '60-Day Comprehensive',
        description: 'Complete interview preparation from beginner to advanced over 60 days.',
        difficulty: 'Hard',
        problemIds: [
        "contains-duplicate",
        "3sum",
        "best-time-to-buy-and-sell-stock",
        "arranging-coins",
        "add-two-numbers",
        "asteroid-collision",
        "balanced-binary-tree",
        "alien-dictionary",
        "find-k-pairs-with-smallest-sums",
        "burst-balloons",
        "design-add-and-search-words-data-structure",
        "counting-bits",
        "find-all-duplicates-in-an-array",
        "4sum",
        "find-all-anagrams-in-a-string",
        "binary-search",
        "copy-list-with-random-pointer",
        "daily-temperatures",
        "binary-tree-level-order-traversal",
        "clone-graph",
        "climbing-stairs",
        "implement-trie-prefix-tree",
        "maximum-xor-of-two-numbers-in-an-array",
        "find-minimum-and-maximum-in-array",
        "container-with-most-water",
        "longest-repeating-character-replacement",
        "capacity-to-ship-packages-within-d-days",
        "intersection-of-two-linked-lists",
        "decode-string",
        "binary-tree-maximum-path-sum",
        "course-schedule",
        "coin-change",
        "replace-words",
        "missing-number",
        "group-anagrams",
        "is-subsequence",
        "longest-substring-without-repeating-characters",
        "find-first-and-last-position-of-element-in-sorted-array",
        "lfu-cache",
        "evaluate-reverse-polish-notation",
        "binary-tree-right-side-view",
        "find-if-path-exists-in-graph",
        "decode-ways",
        "search-suggestions-system",
        "number-of-1-bits",
        "longest-consecutive-sequence",
        "remove-duplicates-from-sorted-array",
        "max-consecutive-ones-iii",
        "find-minimum-in-rotated-sorted-array",
        "linked-list-cycle",
        "generate-parentheses",
        "binary-tree-vertical-order-traversal",
        "flood-fill",
        "distinct-subsequences",
        "word-search-ii",
        "power-of-two",
        "majority-element",
        "remove-element",
        "minimum-size-subarray-sum",
        "find-peak-element",
        "lru-cache",
        "largest-rectangle-in-histogram",
        "binary-tree-zigzag-level-order-traversal",
        "graph-valid-tree",
        "edit-distance",
        "reverse-bits",
        "move-zeroes",
        "shortest-unsorted-continuous-subarray",
        "minimum-window-substring",
        "first-bad-version",
        "merge-two-sorted-lists",
        "min-stack",
        "construct-binary-tree-from-preorder-and-inorder-traversal",
        "max-area-of-island",
        "fibonacci-number",
        "single-number-ii",
        "next-permutation",
        "squares-of-a-sorted-array",
        "permutation-in-string",
        "guess-number-higher-or-lower",
        "palindrome-linked-list",
        "next-greater-element-i",
        "count-good-nodes-in-binary-tree",
        "min-cost-to-connect-all-points",
        "house-robber-ii",
        "sum-of-two-integers",
        "pascals-triangle",
        "trapping-rain-water",
        "sliding-window-maximum",
        "koko-eating-bananas",
        "remove-nth-node-from-end-of-list",
        "remove-k-digits",
        "diameter-of-binary-tree",
        "network-delay-time",
        "house-robber",
        "product-of-array-except-self",
        "two-sum-ii-input-array-is-sorted",
        "subarray-product-less-than-k",
        "median-of-two-sorted-arrays",
        "reorder-list",
        "valid-parentheses",
        "flatten-binary-tree-to-linked-list",
        "number-of-connected-components-in-an-undirected-graph",
        "interleaving-string",
        "reverse-array",
        "valid-palindrome",
        "peak-index-in-a-mountain-array",
        "reverse-linked-list",
        "invert-binary-tree",
        "number-of-islands",
        "jump-game",
        "rotate-array",
        "search-a-2d-matrix",
        "sort-list",
        "kth-smallest-element-in-a-bst",
        "pacific-atlantic-water-flow",
        "longest-common-subsequence",
        "set-matrix-zeroes",
        "search-in-rotated-sorted-array",
        "lowest-common-ancestor-of-a-binary-search-tree"
]
    }
];

export class RoadmapController {
    public static async getRoadmaps(req: AuthRequest, res: Response): Promise<void> {
        try {
            const firebaseUid = req.firebaseUid;
            if (!firebaseUid) {
                res.status(401).json({ message: 'Unauthorized' });
                return;
            }

            const user = await User.findOne({ firebaseUid });
            if (!user) {
                res.status(404).json({ message: 'User not found' });
                return;
            }

            const progressMapObj = Object.fromEntries(user.progress || new Map());

            const result = ROADMAPS.map(roadmap => {
                let solvedCount = 0;
                const problems = roadmap.problemIds.map(pid => {
                    const probInfo = ProblemRegistryService.getProblem(pid);
                    const isCompleted = progressMapObj[pid] === true;
                    if (isCompleted) solvedCount++;
                    return {
                        id: pid,
                        title: probInfo ? probInfo.title : pid.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' '),
                        category: probInfo ? probInfo.category : 'Unknown',
                        difficulty: probInfo ? probInfo.difficulty : 'Medium',
                        isCompleted
                    };
                });

                const totalCount = roadmap.problemIds.length;
                const completionPercentage = totalCount > 0 ? Math.round((solvedCount / totalCount) * 100) : 0;
                const readinessMetric = completionPercentage;

                return {
                    id: roadmap.id,
                    name: roadmap.name,
                    description: roadmap.description,
                    difficulty: roadmap.difficulty,
                    completionPercentage,
                    readinessMetric,
                    problems
                };
            });

            res.json(result);
        } catch (error) {
            console.error('Error fetching roadmaps:', error);
            res.status(500).json({ message: 'Server error' });
        }
    }
}
